.TH TOKEN_CLIPBOARD_COPIER 1 "August 1, 2023"
.SH NAME
token_clipboard_copier \- copy files to clipboard in chunks
.SH SYNOPSIS
.B token_clipboard_copier
.RI [ directory pattern ]
.SH DESCRIPTION
This utility reads all files in the provided directory matching the given pattern, and copies their contents into the clipboard in chunks. Each chunk is no larger than 4096 tokens. The user is prompted to manually paste each chunk before the next one is copied to the clipboard.
.PP
The directory argument is a path to the directory to search for files. The pattern argument is a glob pattern used to match filenames within the directory. For example, "*.txt" matches all text files.
.SH EXAMPLES
token_clipboard_copier src/components "*.tsx"
.br
This will read all TypeScript (.tsx) files in the src/components directory.
.SH AUTHOR
Yoshisaur
.SH REPORTING BUGS
Report bugs to e205723@ie.u-ryukyu.ac.jp.
.SH COPYRIGHT
Copyright © 2023 Yoshisaur. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
